FROM postgres:16-alpine

ENV POSTGRES_USER 'zapal'
ENV POSTGRES_PASSWORD 'zapal'
ENV POSTGRES_DB 'zapal'

COPY load-extensions.sh /docker-entrypoint-initdb.d/
RUN chmod 755 /docker-entrypoint-initdb.d/load-extensions.sh
