FROM mcr.microsoft.com/devcontainers/typescript-node:20-bookworm

# RUN apt install postgresql-client

# Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends <your-package-list-here>

RUN su node -c "npm install -g pnpm"
