import { LinkToDoc as LinkToDoc_29 } from '@payloadcms/plugin-search/client';
import {
  MetaDescriptionComponent as MetaDescriptionComponent_26,
  MetaImageComponent as MetaImageComponent_27,
  MetaTitleComponent as MetaTitleComponent_25,
  OverviewComponent as OverviewComponent_24,
  PreviewComponent as PreviewComponent_28,
} from '@payloadcms/plugin-seo/client';
import {
  AlignFeatureClient as AlignFeatureClient_16,
  BlockquoteFeatureClient as BlockquoteFeatureClient_20,
  BlocksFeatureClient as BlocksFeatureClient_18,
  BoldFeatureClient as BoldFeatureClient_14,
  ChecklistFeatureClient as ChecklistFeatureClient_22,
  HeadingFeatureClient as HeadingFeatureClient_3,
  HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_19,
  IndentFeatureClient as IndentFeatureClient_23,
  InlineCodeFeatureClient as InlineCodeFeatureClient_11,
  InlineToolbarFeatureClient as InlineToolbarFeatureClient_4,
  ItalicFeatureClient as ItalicFeatureClient_15,
  LinkFeatureClient as LinkFeatureClient_6,
  OrderedListFeatureClient as OrderedListFeatureClient_9,
  ParagraphFeatureClient as ParagraphFeatureClient_17,
  RelationshipFeatureClient as RelationshipFeatureClient_21,
  RichTextCell as RichTextCell_0,
  RichTextField as RichTextField_1,
  StrikethroughFeatureClient as StrikethroughFeatureClient_12,
  SubscriptFeatureClient as SubscriptFeatureClient_7,
  SuperscriptFeatureClient as SuperscriptFeatureClient_8,
  UnderlineFeatureClient as UnderlineFeatureClient_13,
  UnorderedListFeatureClient as UnorderedListFeatureClient_10,
  UploadFeatureClient as UploadFeatureClient_5,
} from '@payloadcms/richtext-lexical/client';
import { getGenerateComponentMap as getGenerateComponentMap_2 } from '@payloadcms/richtext-lexical/generateComponentMap';

import { Logo as Logo_31 } from '@cms/components/Logo';
import { NavLogo as NavLogo_30 } from '@cms/components/NavLogo';

export const importMap = {
  '@payloadcms/richtext-lexical/client#RichTextCell': RichTextCell_0,
  '@payloadcms/richtext-lexical/client#RichTextField': RichTextField_1,
  '@payloadcms/richtext-lexical/generateComponentMap#getGenerateComponentMap': getGenerateComponentMap_2,
  '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient_3,
  '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient_4,
  '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient_5,
  '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient_6,
  '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient_7,
  '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient_8,
  '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient_9,
  '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient_10,
  '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient_11,
  '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient_12,
  '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient_13,
  '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient_14,
  '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient_15,
  '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient_16,
  '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient_17,
  '@payloadcms/richtext-lexical/client#BlocksFeatureClient': BlocksFeatureClient_18,
  '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient_19,
  '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient_20,
  '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient_21,
  '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient_22,
  '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient_23,
  '@payloadcms/plugin-seo/client#OverviewComponent': OverviewComponent_24,
  '@payloadcms/plugin-seo/client#MetaTitleComponent': MetaTitleComponent_25,
  '@payloadcms/plugin-seo/client#MetaDescriptionComponent': MetaDescriptionComponent_26,
  '@payloadcms/plugin-seo/client#MetaImageComponent': MetaImageComponent_27,
  '@payloadcms/plugin-seo/client#PreviewComponent': PreviewComponent_28,
  '@payloadcms/plugin-search/client#LinkToDoc': LinkToDoc_29,
  '@cms/components/NavLogo#NavLogo': NavLogo_30,
  '@cms/components/Logo#Logo': Logo_31,
};
